### ISSUE TITLE
Bugs in add_points (line 78)

### ISSUE THREAD

**Issue by Omnistic** [kevinyamauchi/PointAnnotator#4]
Hello, and thank you for the tutorial.

I had issues running the code. First, I think that if one specifies an edge_width > 1.0, the parameter edge_width_is_relative should be set to True. Otherwise, you get a: "ValueError: edge_width_is_relative can only be enabled if edge_width is between 0 and 1".

The second issue I had was with the data parameter. If I run the code as is, I get a: "ValueError: Length of values (3) does not match length of index (0)". Changing data from empty((0, 3)) to empty((3, 3)) seems to fix the problem, but I don't know why (if someone can explain, I'd be grateful). This is how I modified the line 78:

`        points_layer = viewer.add_points(
            data=np.empty((3, 3)),
            properties={'label': labels},
            edge_color='label',
            edge_color_cycle=COLOR_CYCLE,
            symbol='o',
            face_color='transparent',
            edge_width=8,
            edge_width_is_relative=False,
            size=12,
        )`

I hope this can help if you are having issues running this code.

Take care,

David

**Comment by andy-sweet** [comment]
I think the second issue is related to the eventual removal of something has been deprecated for a while (since v0.4.11), which is using the `properties` parameter to define possible values. See [napari PR #5041](https://github.com/napari/napari/pull/5041/files#diff-0f1588377d587a70fc4bdd1dc19e5d0036b98029a9651f7d3a7d87815ab4f210L348) for the removal which likely made it in to v0.4.17.

The better fix is to use `property_choices` instead of `properties`, so you don't need to specify empty data, which may be spurious. Using `property_choices` may be deprecated in v0.5, so we'll need another update here in the future, but this should be good for now.

As part of my work on https://github.com/napari/docs/pull/145, I'm also going to make a PR to this repo so things are working for the upcoming v0.4.19 release.

**Comment by kevinyamauchi** [comment]
I believe this was fixed in #5. Please feel free to re-open if you are still experiencing this bug.
